source/JumpStart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from splash.views import \
    index  # probably bad coding practice but, it defaults to a "splash" screen

admin.autodiscover()
from django.conf import settings
from django.conf.urls.static import static
import accounts.views
import workshops.views
import importing.views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^splash/', include('splash.url')),
    url(r'^temporary/', include('temporary.url')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', index, name='index'),  # goes to splash.views.index and loads splash_index_page, bad coding practive
    url(r'^workshops/', include('workshops.urls')),
    url(r'^$', index, name='index'),
    url(r'^csv_upload', importing.views.csv_upload_page, name='csv_upload'),
    url(r'^email_template', importing.views.email_template_page,
        name='email_template'),
    # goes to splash.views.index and loads splash_index_page, bad coding practive
    url(r'^workshops/', workshops.views.createWorkshop, name='workshops'),
]

source/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signUp, name='signup'),
    url(r'^login/', views.loginView, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
]

source/workshops/urls.py
from django.conf.urls import url
from . import views

app_name = 'workshop'

urlpatterns = [
  #  url(r'^create/', views.createWorkshop, name='create_workshop'),
   # url(r'^(?P<pk>[0-9]+)/csv_upload', views.csv_upload_page, name='csv_upload'),
   # url(r'^(?P<pk>[0-9]+)/createSession', views.createSession, name='createSession'),
   # url(r'^(?P<pk>[0-9]+)/bulkemail', views.bulk_email_page, name='bulkemail'),
   # url(r'^(?P<pk>[0-9]+)/', views.workshop_details, name='workshopdetails'),
    url(r'^(?P<pk>[0-9]+)/pdf', views.GeneratePDF, name='generatePDF'),
    url(r'survey/make/(?P<pk>[0-9]+)', views.createQuestionsForSurvey, name='createsurvey'),
    url(r'^create/$', views.createWorkshop, name='create_workshop'),
    url(r'^(?P<pk>[0-9]+)/csv_upload', views.csv_upload_page, name='csv_upload'),
    url(r'^(?P<pk>[0-9]+)/createSession', views.createSession, name='createSession'),
    url(r'^(?P<pk>[0-9]+)/bulkemail', views.bulk_email_page, name='bulkemail'),
    url(r'^(?P<pk>[0-9]+)/', views.workshop_details, name='workshopdetails'),
    url(r'^survey/(?P<survey_id>\d+)/$', views.survey_render_function, name='takesurvey'),
    url(r'^survey/(?P<survey_id>\d+)/(?P<uuid>[0-9a-f\-]+)', views.survey_render_function, name='takesurvey'),
#/workshops/survey/{{ survey_id }}/{{ uuid }}
    #http://localhost:8000/workshops/survey/2/<uuid>
    url(r'survey/make/$', views.createQuestionsForSurvey, name='createsurvey'),
]

source/templates/email_template_page.html
{% extends 'navbar.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Prepare Email for Bulk Sending</title>
</head>
<h1>Prepare Email for Bulk Sending</h1>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send Bulk Email</button>
</form>

<!--<p><a href="{% url 'index' %}">Return to home</a></p>-->
</body>
</html>
{% endblock %}

source/templates/emails_have_been_sent.html
<!DOCTYPE html>
<html>

<style>
    form {
        border: 3px solid #f1f1f1;
    }

    input[type=text], input[type=password] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        box-sizing: border-box;
    }

    button {
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
    }

    button:hover {
        opacity: 0.8;
    }

    .cancelbtn {
        width: auto;
        padding: 10px 18px;
        background-color: #f44336;
    }

    .imgcontainer {
        text-align: center;
        margin: 24px 0 12px 0;
    }

    img.avatar {
        width: 20%;
        border-radius: 40%;
    }

    .container {
        padding: 16px;
    }

    span.psw {
        float: right;
        padding-top: 16px;
    }

    /* Change styles for span and cancel button on extra small screens */
    @media screen and (max-width: 300px) {
        span.psw {
            display: block;
            float: none;
        }

        .cancelbtn {
            width: 100%;
        }
    }
</style>
<body>

<h2><img src="http://i63.tinypic.com/b6a683.jpg" border="0"
         alt="Image and video hosting by TinyPic"></h2>
<form action="/action_page.php">
    <div class="imgcontainer">
        <img src=http://education.utsa.edu/images/uploads/Rowdy_Head.gif
             alt="Avatar" class="avatar">
    </div>
    <h1>Email has been sent</h1>
</body>
</html>

source/templates/invoice.html
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
 <html>
     <head>
         <title>Title</title>
         <style type="text/css">
             body {
                 font-weight: 200;
                 font-size: 14px;
             }
             .header {
                 font-size: 20px;
                 font-weight: 100;
                 text-align: center;
                 color: #007cae;
             }
             .title {
                 font-size: 22px;
                 font-weight: 100;
                /* text-align: right;*/
                padding: 10px 20px 0px 20px;
             }
             .title span {
                 color: #007cae;
             }
             .details {
                 padding: 10px 20px 0px 20px;
                 text-align: left !important;
                 /*margin-left: 40%;*/
             }
             .hrItem {
                 border: none;
                 height: 1px;
                 /* Set the hr color */
                 color: #333; /* old IE */
                 background-color: #fff; /* Modern Browsers */
             }
         </style>
     </head>
     <body>
         <div class='wrapper'>
             <div class='header'>
                 <p class='title'>Invoice # </p>
             </div>
         <div>
         <div class='details'>
             Bill to: <br/>
             Amount:  <br/>
             Date:
             <hr class='hrItem' />
         </div>
     </div>
     </body>
 </html>

source/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>JumpStart</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="mynav">
          <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                  <li><a href="{% url 'index' %}">Home</a></li>
                  <li><a href="#" onClick="document.getElementById('logout').submit()">Logout</a></li>
                  <form id = "logout" method="POST" action = "{% url 'accounts:logout' %}">
                    {% csrf_token %}
                    <input type="hidden">
                  </form>

              {% else %}
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
    {%  block content %}
    {% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

source/templates/send_email_registrations.html
{% extends 'navbar.html' %}
{% block content %}

<!DOCTYPE html>
<html>

<style>
    form {
        border: 3px solid #f1f1f1;
    }

    input[type=text], input[type=password] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        box-sizing: border-box;
    }

    button {
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
    }

    button:hover {
        opacity: 0.8;
    }

    .cancelbtn {
        width: auto;
        padding: 10px 18px;
        background-color: #f44336;
    }

    .imgcontainer {
        text-align: center;
        margin: 24px 0 12px 0;
    }

    img.avatar {
        width: 20%;
        border-radius: 40%;
    }

    .container {
        padding: 16px;
    }

    span.psw {
        float: right;
        padding-top: 16px;
    }

    /* Change styles for span and cancel button on extra small screens */
    @media screen and (max-width: 300px) {
        span.psw {
            display: block;
            float: none;
        }

        .cancelbtn {
            width: 100%;
        }
    }
</style>
<div>

    <img src="http://i63.tinypic.com/b6a683.jpg" border="0"
             alt="Image and video hosting by TinyPic">
    <h2>Welcome '{{ request.user.username }}' </h2>
    <br />
    {% if workshops %}

        <h3>Your Workshops:</h3>
        {% for workshop in workshops %}
            {% if workshop.owner == user %}
                <table>
                    <tr>
                        <td><a href="{% url 'workshop:workshopdetails' workshop.id %}">{{ workshop.title}}</a><br />
                    {{ workshop.pub_date }} by {{ workshop.owner.username}}</td>
                    </tr>
                </table>
                <br />
            {% endif%}
        {% endfor %}
    {% endif %}
            <a class = "btn btn-primary" href = "{% url 'workshop:create_workshop' %}"> Create new Workshop</a>
              <br />



    <form action="/action_page.php">
        <div class="imgcontainer">
            <img src=http://education.utsa.edu/images/uploads/Rowdy_Head.gif
                 alt="Avatar" class="avatar">
        </div>

    <!--</form>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit"/>
        <br>
        <br \>
        <a href="{% url 'csv_upload' %}">Import Emails from CSV</a>
        <br \>
        <a href="{% url 'email_template' %}">Add Template Email</a>
        <br \>-->
    </form>
</div>
<br \>

</html>

{% endblock %}

source/templates/thanks_for_registering.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Thanks for Registering for the workshop! Your UUID is {{ uuid_name }},
Registration has been confirmed
</body>
</html>