source/JumpStart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from splash.views import \
    index  # probably bad coding practice but, it defaults to a "splash" screen

admin.autodiscover()
from django.conf import settings
from django.conf.urls.static import static
import accounts.views
import workshops.views
import importing.views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^splash/', include('splash.url')),
    url(r'^temporary/', include('temporary.url')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', index, name='index'),  # goes to splash.views.index and loads splash_index_page, bad coding practive
    url(r'^workshops/', include('workshops.urls')),
    url(r'^$', index, name='index'),
    url(r'^csv_upload', importing.views.csv_upload_page, name='csv_upload'),
    url(r'^email_template', importing.views.email_template_page,
        name='email_template'),
    # goes to splash.views.index and loads splash_index_page, bad coding practive
    url(r'^workshops/', workshops.views.createWorkshop, name='workshops'),
]

source/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signUp, name='signup'),
    url(r'^login/', views.loginView, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
]

source/workshops/urls.py
from django.conf.urls import url
from . import views

app_name = 'workshop'

urlpatterns = [
  #  url(r'^create/', views.createWorkshop, name='create_workshop'),
   # url(r'^(?P<pk>[0-9]+)/csv_upload', views.csv_upload_page, name='csv_upload'),
   # url(r'^(?P<pk>[0-9]+)/createSession', views.createSession, name='createSession'),
   # url(r'^(?P<pk>[0-9]+)/bulkemail', views.bulk_email_page, name='bulkemail'),
   # url(r'^(?P<pk>[0-9]+)/', views.workshop_details, name='workshopdetails'),
    url(r'^(?P<pk>[0-9]+)/pdf', views.GeneratePDF, name='generatePDF'),
    url(r'survey/make/(?P<pk>[0-9]+)', views.createQuestionsForSurvey, name='createsurvey'),
    url(r'^create/$', views.createWorkshop, name='create_workshop'),
    url(r'^(?P<pk>[0-9]+)/csv_upload', views.csv_upload_page, name='csv_upload'),
    url(r'^(?P<pk>[0-9]+)/createSession', views.createSession, name='createSession'),
    url(r'^(?P<pk>[0-9]+)/bulkemail', views.bulk_email_page, name='bulkemail'),
    url(r'^(?P<pk>[0-9]+)/', views.workshop_details, name='workshopdetails'),
    url(r'^survey/(?P<survey_id>\d+)/$', views.survey_render_function, name='takesurvey'),
    url(r'^survey/(?P<survey_id>\d+)/(?P<uuid>[0-9a-f\-]+)', views.survey_render_function, name='takesurvey'),
#/workshops/survey/{{ survey_id }}/{{ uuid }}
    #http://localhost:8000/workshops/survey/2/<uuid>
    url(r'survey/make/$', views.createQuestionsForSurvey, name='createsurvey'),
]

source/workshops/models.py
from django.db import models
from django.contrib.auth.models import User
from importing import models as ImportingModels



# Create your models here.


class Workshop(models.Model):
    title = models.CharField(max_length=30)
    pub_date = models.DateField()
    owner = models.ForeignKey(User, default="Admin")

    def __str__(self):
        return self.title





class session(models.Model):
    session_title = models.CharField(max_length=48,default="title")
    session_location = models.CharField(max_length=48,default="CS Main Lab")
    session_date = models.DateTimeField(default="1987-01-01 00:00")
    session_threshold = models.IntegerField(default= 1)
    workshop = models.ForeignKey(Workshop, default=1)
    registered_attendees = models.ManyToManyField(ImportingModels.attendee, default=None)



    #This should create a many to many relationship between this session and the attendee to be registered
    def register(self,this_session, attendee_to_register):
        if type(attendee_to_register) == ImportingModels.attendee and type(this_session) == session:
            this_session.registered_attendees.add(attendee_to_register)
        return  self



class Survey(models.Model):
    title = models.CharField(max_length=60)
    creator = models.CharField(max_length=60)
    threshold = models.FloatField(max_length=3)
    pub_date = models.DateField()
    workshop = models.ForeignKey(Workshop)


    def __str__(self):
        return self.title


class Question(models.Model):
    body_text = models.TextField()
    survey = models.ForeignKey(Survey)

    def __str__(self):
        return self.body_text

from enum import Enum
class QuestionValues(Enum):
    NOKNOWLEDGE = 1
    VERYLITTLEKNOWLEDGE = 2
    SOMEKNOWLEDGE = 3
    Familiar = 4
    EXPERIENCED = 5


class AnsweredQuestions(models.Model):
    KNOWLEDGE_IN_SUBJECT = (
        (QuestionValues.NOKNOWLEDGE.value, 'No Knowledge'),
        (QuestionValues.VERYLITTLEKNOWLEDGE.value, 'Very little Knowledge'),
        (QuestionValues.SOMEKNOWLEDGE.value, 'Some'),
        (QuestionValues.Familiar.value, 'Familiar'),
        (QuestionValues.EXPERIENCED.value, 'Experienced'),
    )

    knowledge_scale = models.CharField(
        max_length=2,
        choices=KNOWLEDGE_IN_SUBJECT,
        default=QuestionValues.SOMEKNOWLEDGE.value,
    )

    question = models.ForeignKey(Question)

    def is_knowledge(self):
        return self.knowledge_scale in (self.NOKNOWLEDGE,
                                        self.VERYLITTLEKNOWLEDGE,
                                        self.SOMEKNOWLEDGE,
                                        self.Familiar,
                                        self.EXPERIENCED,
                                        )

source/workshops/forms.py
from django import forms
from workshops.models import session

class Session_Form(forms.ModelForm):
    class Meta:
        model = session
        fields = ('session_title','session_date', 'session_location','session_threshold','workshop')

source/workshops/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
import pdb

from django.shortcuts import render, get_object_or_404
from importing.models import attendee as AttendeeObject, csv_file as CSVObject
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from importing.forms import CSV_Form, Email_Template_Form
from workshops.forms import Session_Form
from temporary.models import \
    attendee_email_workshop_uuid_association as AssociationObject
import re
from django.contrib.auth.decorators import login_required
from . import models
from .models import Workshop, session as SessionObject
from django.template.loader import get_template
from django.utils import datetime_safe
from django.http import HttpResponse
from django.views.generic import View

from .utils import render_to_pdf #created in step 4



# Create your views here.


globalListOfAttenddes = []

def GeneratePDF(request,pk):
    template = get_template('workshops/invoice.html')
    workshop = get_object_or_404(Workshop, pk=pk)
    workshop_associations = AssociationObject.objects.filter(workshop_local=workshop)
    context = {
        'workshop':workshop ,
        'workshop_associations':workshop_associations,
    }
    html = template.render(context)
    pdf = render_to_pdf('workshops/invoice.html',context)
    if pdf:
        response = HttpResponse(pdf, content_type= 'application/pdf')
        filename = "Sign_Up_Sheet_%s.pdf" %(workshop.title)
        content = "inline; filename ='%s'" %(filename)
        download = request.GET.get('download')
        if download:
            content = "attachment; filename ='%s'" %(filename)
        response['Content-Disposition'] = content
        return response
    return HttpResponse('Not found')

@login_required(login_url='/login/')
def createWorkshop(request):
    if request.method == 'POST':
        if request.POST['title']:
            workshop = Workshop()
            workshop.title = request.POST['title']
            workshop.pub_date = timezone.datetime.now()
            workshop.owner = request.user
            workshop.save()
            return redirect('/?next=/')
        else:
            return render(request, 'workshops/workshops.html',
                          {'error': 'ERROR: You must include a Title'})
    else:
        return render(request, 'workshops/workshops.html')

def workshop_details(request,pk):
        workshop = get_object_or_404(Workshop, pk=pk)
        workshop_associations = AssociationObject.objects.filter(workshop_local=workshop)
        sessions  = SessionObject.objects.filter(workshop=workshop)
        survey_list = models.Survey.objects.filter(workshop = workshop)
        survey = None
        for x in survey_list:
            survey = x

        attending = globalListOfAttenddes


        return render(request,'workshops/workshopdetails.html',{'workshop':workshop,
                                                                'workshop_associations':workshop_associations,
                                                                'sessions':sessions,
                                                                'survey': survey,
                                                                'attending':attending,
                                                                })


def createSession(request, pk):
    workshop = get_object_or_404(Workshop, pk=pk)
    if(request.method =="POST"):
        form = Session_Form(request.POST)
        if form.is_valid():
            try :#object exists
               session = SessionObject.objects.get(workshop=workshop,session_title=form.cleaned_data['session_title'])
               error = 'session already exists'
               form = Session_Form()
               return render(request, 'workshops/createSession.html', {'error':error,'form':form})
            except:#object does not exist
                session = SessionObject.objects.create(workshop=workshop)
                session.session_title = form.cleaned_data['session_title']
                session.session_date = form.cleaned_data['session_date']
                session.session_location = form.cleaned_data['session_location']
                session.session_threshold = form.cleaned_data['session_threshold']
                session.save()
                return redirect('workshops/workshopdetails.html')
    #set values for session from form
    else:
        form = Session_Form()
        return render(request, 'workshops/createSession.html', {'workshop': workshop, 'form': form})



@login_required(login_url='accounts/login/')
def bulk_email_page(request, pk):
    if request.method == "POST":
        form = Email_Template_Form(request.POST)
        if form.is_valid():
            workshop = get_object_or_404(Workshop, pk=pk)
            workshop_associations = AssociationObject.objects.filter(workshop_local=workshop)
            survey = models.Survey.objects.all()
            last_survey = survey.reverse()[0]

            print(last_survey.id)
            for association in workshop_associations:
                temp_attendee = association.attendee_local

                #may need to change
                email_string = "http://" + str(
                    request.get_host()) + "/workshops/survey/" +str(last_survey.id)+ "/" +\
                    str(association.uuid_token)


#survey/(?P<survey_id>\d+)/(?P<uuid>[0-9a-f\-]+)


                temp_body = form.cleaned_data['email_body'] + "\nPlease take your survey here!:\n" + email_string + "\n\n" + form.cleaned_data['email_signature'] + "\n"



                send_mail(
                    form.cleaned_data['email_subject'],
                    temp_body,
                    form.cleaned_data['email_signature'],
                    [temp_attendee.email],
                    fail_silently=False
                )
                return redirect('/workshops/1/')


            # form.save()
            # email to a user
            # ensure that all fields are filled out or error
            # redirect page confirming success
    else:
        form = Email_Template_Form()
    return render(request, "email_template_page.html", {'form': form})


def process_file(form, f, workshop):
    # gets group name from form, will need to get from workshop in future, possibly rename to workshop name
    group_name = form.cleaned_data['group']
    #group_name = workshop.title should not be used as an invitee can be associated with multiple workshops

    for line in f:
        # Convert file bytes into string so that it can use split.
        lineS = str(line, 'utf-8')
        lineL = lineS.split(',')
        # attempts to split csv line into array with 12 indexes until EOF
        if len(lineL) != 12:
            # checks for abc123 in group instead, and possibly
            # overwrite existing db entry in case of email address change
            try:
                attendee = AttendeeObject.objects.get(utsa_id=lineL[6])
            except ObjectDoesNotExist:
                # checks to see if the first data member is a digit,
                # then checks that email and abc123 are vaild
                if re.match(r"\d+", lineL[0]) and re.match(
                        r"^[\w.]+@[\w.]+$", lineL[10]) \
                        and re.match(r"^[a-z]{3}[0-9]{3}$",
                                     lineL[6]):
                    attendee = AttendeeObject.objects.create(
                        utsa_id=lineL[6], last_name=lineL[7],
                        first_name=lineL[8],
                        email=lineL[10], group=group_name)
                    attendee.save()
                    try:
                        workshop_association = AssociationObject.objects.get(attendee_utsa_id=attendee.utsa_id,
                                                                             workshop_local=workshop)
                    except ObjectDoesNotExist:
                        workshop_association = AssociationObject.objects.create(attendee_local=attendee,
                                                                                attendee_utsa_id = attendee.utsa_id,
                                                                                workshop_local=workshop)
                        workshop_association.save()
                    else:
                        if(workshop_association.attendee != attendee):
                            workshop_association.attendee_local = attendee
                            workshop_association.attendee_clicked_link_local = False
                            workshop_association.save()
                else:
                    pass
            else:
                # If exception was not called and emails differ,
                # overwrite database entry's email and group name
                if re.match(r"\d+", lineL[0]) and re.match(
                        r"^[\w.]+@[\w.]+$",
                        lineL[10]) and attendee.email != lineL[10] \
                        and attendee.group != group_name:
                    attendee.email = lineL[10]
                    attendee.group = group_name
                    attendee.save()
                    # create association between workshop and attendee after import attempt
                    # this should work once workshop object is implemented
                #import ipdb
                #ipdb.set_trace()
                try:
                    workshop_association = AssociationObject.objects.get(attendee_utsa_id=attendee.utsa_id, workshop_local= workshop)
                except ObjectDoesNotExist:
                    workshop_association = AssociationObject.objects.create(attendee_local=attendee,
                                                                            attendee_utsa_id = attendee.utsa_id,

source/workshops/templates/workshops/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>JumpStart</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="mynav">
          <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}

                    {% csrf_token %}
                    <input type="hidden">
                  </form>

              {% else %}
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
    {%  block content %}
    {% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

source/workshops/templates/workshops/complete_survey.html
{% extends 'workshops/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<h1>Thank you for taking this survey</h1>
Number of Questions: {{ num_questions }} <br>
Total: {{ total }} <br>
Average: {{ avg }} <br>
<br/>
           {%if sessionList%}
             You should attend the following Sessions:
            {%endif %}
            <br/>
            <br/>
            {% for sessions in sessionList %}
               {{ sessions.session_title }} at {{sessions.session_location}} on {{sessions.session_date}}<br/>
               <!--- <input type="radio" name="question_{{ question.id}}" value="{{ value }}"> {{ choice }} --->
            {% endfor %}

</body>
</html>
{% endblock %}

source/workshops/templates/workshops/createSession.html
{% extends 'navbar.html' %}

{% block content %}

<h1> Create session for : {{workshop.title }}</h1>

{% if error %}
{{ error }}
<br/>
<br/>
{% endif %}

<form method="POST" action="">
    {% csrf_token %}
    Sesssion:
    <br/>
    {{ form.as_p }}
    <br/>
    <br />
    <input class = "btn btn-primary" type="submit" value="Post"/>
</form>
{% if error %}
    {{ error }}
    {% endif %}
{% endblock %}

source/workshops/templates/workshops/csv_upload.html
{% extends 'navbar.html' %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSV File Upload</title>
</head>
<h2><a  href = "{% url 'workshop:workshopdetails' workshop.id %} "> {{ workshop.title }}</a></h2>

<h1>CSV File Upload</h1>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
<h4>{% if success %} {{ success }}{% endif %}</h4>

</body>
</html>
{% endblock %} }}

source/workshops/templates/workshops/invoice.html
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
 <html>
     <head>
         <title>Sign Up For {{ workshop.title }}</title>
         <style type="text/css">
             body {
                 font-weight: 200;
                 font-size: 14px;
             }
             .header {
                 font-size: 20px;
                 font-weight: 100;
                 text-align: center;
                 color: #007cae;
             }
             .title {
                 font-size: 22px;
                 font-weight: 100;
                /* text-align: right;*/
                padding: 10px 20px 0px 20px;
             }
             .title span {
                 color: #007cae;
             }
             .details {
                 padding: 10px 20px 0px 20px;
                 text-align: left !important;
                 /*margin-left: 40%;*/
             }
             .hrItem {
                 border: none;
                 height: 1px;
                 /* Set the hr color */
                 color: #333; /* old IE */
                 background-color: #fff; /* Modern Browsers */
             }


                table {
                font-family: arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
            }

            td, th {
                border: 1px solid #dddddd;
                text-align: left;
                padding: 5px;
            }

            tr:nth-child(even) {
                background-color: #dddddd;
            }

         </style>
     </head>
     <body>
         <div class='wrapper'>
             <div class='header'>
                 <p class='title'>Sign Up Sheet for {{ workshop.title }} </p>
             </div>

    <table>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Signature</th>
      </tr>
      {% for association in workshop_associations %}
        <tr>
            <td> {{ association.attendee_local.first_name}} {{ association.attendee_local.last_name }}</td>
            <td> {{ association.attendee_local.email }}  </td>
            <td>   </td>
        </tr>
      {% endfor %}

    </table>


     </body>
 </html>

source/workshops/templates/workshops/present_survey.html
{% extends 'workshops/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<h1>Questions</h1>
<form action="/workshops/survey/{{ survey_id }}/{{ uuid }}" method="post">
{% csrf_token %}
    <ol>
        {%  for question in list_of_questions %}
            <li>{{ question.body_text }}</li>
            {% for value, choice in form %}
                <input type="radio" name="question_{{ question.id}}" value="{{ value }}"> {{ choice }}
            {% endfor %}
            <br><br>
        {%  endfor %}
    </ol>
<button type="submit">Submit</button>
</form>
</body>
</html>
{% endblock %}

source/workshops/templates/workshops/survey.html
{% extends 'workshops/base.html' %}
{% block content %}
<html>
<header>
    <style>
        .question{
            width:80%;
        }
        li{
            margin-bottom:15px;
        }
    </style>
</header>
<body>
<form action="/workshops/survey/make/" name="createsurvey" method="post" title="survey_data">
    {% csrf_token %}
    <h2>Name of your survey </h2><br />
    <input  type='text' name='survey_title_form' placeholder='Name of Survey',title="survey_name">
    <br/>
    <br />
        <a class="glyphicon glyphicon-plus-sign" id="addBtn"> Add question</a>

    <ol id="survey"></ol>
    <br />
   <!--- <input type='text' name='threshold' placeholder='Score threshold' title='threshold'>
    <br /> --->

    <br/>
    <input class = "btn btn-primary" type="submit">

</form>

</body>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    var questionHtml = "<li><input class='question' type='text' name='questions' placeholder='Enter a question'></input><button class='removeQuestion' >x</button></li>"
    var addButton = $("#addBtn");
    var surveyForm = $("#survey");

    addButton.on('click', function(){
        surveyForm.append(questionHtml);
    });

    surveyForm.on('click', '.removeQuestion', function(e){
        e.preventDefault();
        $(this).parent().remove();
    });

</script>

</html>

{% endblock %}

source/workshops/templates/workshops/workshopdetails.html
{% extends 'navbar.html' %}

{% block content %}
    <h1>Welcome to workshop {{ workshop.title }}</h1>
    <br/>
    <h3>-Sessions</h3>
    {% for session in sessions %}
        {{ session.session_title }} : {{ session.session_date }}
        <br />
    {% endfor %}
    <a class = "btn btn-primary" href = "{% url 'workshop:createSession' workshop.id%}"> Create New Session</a>
    <br/>
    <br/>
    <h3>-Add invitees to your workshop</h3>
    <a class = "btn btn-primary" href = "{% url 'workshop:csv_upload' workshop.id%}"> CSV Upload</a>
    <br/>
    <br/>
    <h3>-List of attendees </h3>
    {% if workshop_associations %}
        {% for association in workshop_associations %}
                {{ association.attendee_local.email }}
                <br />
        {% endfor %}
        <a class = "btn btn-primary" href = "{% url 'workshop:bulkemail' workshop.id %} "> Send Emails</a>
        <a class = "btn btn-primary" href = "{% url 'workshop:generatePDF' workshop.id %} "> PDF</a>

    {% endif %}
    <br/>
    <br/>
    {% if attending %}
    <h3>-People who should be attending the workshop</h3>
        {% for email in attending %}
            {{email}}
        {% endfor%}
    {% endif %}





    <br/>
    <br/>
    <h3>-Create survey for the workshop</h3>
    {% if survey %}
        {{survey.title}}
        <br/>
    {% endif %}

   <a class = "btn btn-primary" href = " {% url 'workshop:createsurvey' workshop.id %}"> Create Survey</a>

    <br />
</div>


{% endblock %} }}

source/workshops/templates/workshops/workshops.html
{% extends 'navbar.html' %}

{% block content %}

<h1> Create New Workshop</h1>

{% if error %}
{{ error }}
<br/>
<br/>
{% endif %}

<form method="POST" action="{url'post:createWorkshop' %}">
    {% csrf_token %}
    Workshop Title:
    <br/>
    <input type="text" name="title"/>
    <br/>
    <br />
    <input class = "btn btn-primary" type="submit" value="Post"/>
</form>

{% endblock %}